name: Build Geographic Library

on:
  push:
    branches:
      - 'devel'
      - 'master'
  workflow_dispatch:
  pull_request:

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: CMake Setup
        run: |
          cmake -S . -B build -G "Visual Studio 17 2022" -DBUILD_SHARED_LIBS:BOOL=OFF -DCMAKE_BUILD_TYPE:STRING=${{env.BUILD_TYPE}} -DCMAKE_INSTALL_PREFIX:PATH=${{github.workspace}}/build/install -DGEOGRAPHICLIB_PRECISION:STRING=2

      - name: CMake Build
        run: cmake --build build/ --config ${{env.BUILD_TYPE}}

      - name: CMake Install
        run: cmake --install build/ --config ${{env.BUILD_TYPE}}

      - name: Run tests
        working-directory: build/tests
        run: ctest -V -C ${{env.BUILD_TYPE}} --output-on-failure
